//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSCISResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSCISResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schválit |.
        /// </summary>
        public static string ACCEPT {
            get {
                return ResourceManager.GetString("ACCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přijmout lekci |.
        /// </summary>
        public static string ACCEPT_LESSON {
            get {
                return ResourceManager.GetString("ACCEPT_LESSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schváleno.
        /// </summary>
        public static string ACCEPTED {
            get {
                return ResourceManager.GetString("ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat předmět.
        /// </summary>
        public static string ADD_SUBJECT {
            get {
                return ResourceManager.GetString("ADD_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN.
        /// </summary>
        public static string ADMIN {
            get {
                return ResourceManager.GetString("ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žadatel.
        /// </summary>
        public static string APPLICANT {
            get {
                return ResourceManager.GetString("APPLICANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Support Centre.
        /// </summary>
        public static string APPLICATION_NAME {
            get {
                return ResourceManager.GetString("APPLICATION_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Účast.
        /// </summary>
        public static string ATTENDANCE {
            get {
                return ResourceManager.GetString("ATTENDANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        public static string AUTHOR {
            get {
                return ResourceManager.GetString("AUTHOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zpět.
        /// </summary>
        public static string BACK {
            get {
                return ResourceManager.GetString("BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušit |.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poznámka ke zrušení.
        /// </summary>
        public static string CANCELLATION_COMMENT {
            get {
                return ResourceManager.GetString("CANCELLATION_COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušeno.
        /// </summary>
        public static string CANCELLED {
            get {
                return ResourceManager.GetString("CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHCI_POMAHAT_HTML_TEXT.
        /// </summary>
        public static string CHCI_POMAHAT_HTML {
            get {
                return ResourceManager.GetString("CHCI_POMAHAT_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentář.
        /// </summary>
        public static string COMMENT {
            get {
                return ResourceManager.GetString("COMMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obsah.
        /// </summary>
        public static string CONTENT {
            get {
                return ResourceManager.GetString("CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete smazat tento obsah?.
        /// </summary>
        public static string CONTENT_DELETE_CONFIRM {
            get {
                return ResourceManager.GetString("CONTENT_DELETE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit.
        /// </summary>
        public static string CREATE {
            get {
                return ResourceManager.GetString("CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit událost.
        /// </summary>
        public static string CREATE_EVENT {
            get {
                return ResourceManager.GetString("CREATE_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit novinku.
        /// </summary>
        public static string CREATE_NEWS {
            get {
                return ResourceManager.GetString("CREATE_NEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořit rozvrhovou akci.
        /// </summary>
        public static string CREATE_SCHEDULE_EVENT {
            get {
                return ResourceManager.GetString("CREATE_SCHEDULE_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvořeno.
        /// </summary>
        public static string CREATED {
            get {
                return ResourceManager.GetString("CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamítnout.
        /// </summary>
        public static string DECLINE {
            get {
                return ResourceManager.GetString("DECLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Známka.
        /// </summary>
        public static string DEGREE {
            get {
                return ResourceManager.GetString("DEGREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smazat uživatele.
        /// </summary>
        public static string DELETE_USER {
            get {
                return ResourceManager.GetString("DELETE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string DETAIL {
            get {
                return ResourceManager.GetString("DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit.
        /// </summary>
        public static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upravit novinku.
        /// </summary>
        public static string EDIT_NEWS {
            get {
                return ResourceManager.GetString("EDIT_NEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upraveno.
        /// </summary>
        public static string EDITED {
            get {
                return ResourceManager.GetString("EDITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upraveno uživatelem.
        /// </summary>
        public static string EDITED_BY {
            get {
                return ResourceManager.GetString("EDITED_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Událost.
        /// </summary>
        public static string EVENT {
            get {
                return ResourceManager.GetString("EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušení události.
        /// </summary>
        public static string EVENT_CANCELLATION {
            get {
                return ResourceManager.GetString("EVENT_CANCELLATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vypsání události.
        /// </summary>
        public static string EVENT_CREATION {
            get {
                return ResourceManager.GetString("EVENT_CREATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete smazat událost?.
        /// </summary>
        public static string EVENT_DELETE_CONFIRMATION {
            get {
                return ResourceManager.GetString("EVENT_DELETE_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail události.
        /// </summary>
        public static string EVENT_DETAIL {
            get {
                return ResourceManager.GetString("EVENT_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lekce.
        /// </summary>
        public static string EVENTS {
            get {
                return ResourceManager.GetString("EVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generuj odkaz pro feedback |.
        /// </summary>
        public static string GENERATE_FEEDBACK_LINK {
            get {
                return ResourceManager.GetString("GENERATE_FEEDBACK_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nadpis.
        /// </summary>
        public static string HEADER {
            get {
                return ResourceManager.GetString("HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domů.
        /// </summary>
        public static string HOME {
            get {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INDEX_HTML_TEXT.
        /// </summary>
        public static string INDEX_HTML {
            get {
                return ResourceManager.GetString("INDEX_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KONTAKT_HTML_TEXT.
        /// </summary>
        public static string KONTAKT_HTML {
            get {
                return ResourceManager.GetString("KONTAKT_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Příjmení.
        /// </summary>
        public static string LASTNAME {
            get {
                return ResourceManager.GetString("LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LOGIN {
            get {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moje lekce.
        /// </summary>
        public static string MY_EVENTS {
            get {
                return ResourceManager.GetString("MY_EVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jméno.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novinky.
        /// </summary>
        public static string NEWS {
            get {
                return ResourceManager.GetString("NEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POTREBUJI_POMOC_HTML_TEXT.
        /// </summary>
        public static string POTREBUJI_POMOC_HTML {
            get {
                return ResourceManager.GetString("POTREBUJI_POMOC_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Počet opakování.
        /// </summary>
        public static string RECURRENCE {
            get {
                return ResourceManager.GetString("RECURRENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string ROLE {
            get {
                return ResourceManager.GetString("ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložit.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studentské číslo.
        /// </summary>
        public static string STUDENT_NUMBER {
            get {
                return ResourceManager.GetString("STUDENT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Předmět.
        /// </summary>
        public static string SUBJECT {
            get {
                return ResourceManager.GetString("SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Předměty.
        /// </summary>
        public static string SUBJECTS {
            get {
                return ResourceManager.GetString("SUBJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Správa předmětů.
        /// </summary>
        public static string SUBJECTS_MANAGEMENT {
            get {
                return ResourceManager.GetString("SUBJECTS_MANAGEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systémové parametry.
        /// </summary>
        public static string SYSTEM_PARAMS {
            get {
                return ResourceManager.GetString("SYSTEM_PARAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas od.
        /// </summary>
        public static string TIME_FROM {
            get {
                return ResourceManager.GetString("TIME_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas do.
        /// </summary>
        public static string TIME_TO {
            get {
                return ResourceManager.GetString("TIME_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozvrh po přihlášení.
        /// </summary>
        public static string TIMETABLE_AFTER_LOGIN {
            get {
                return ResourceManager.GetString("TIMETABLE_AFTER_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TUTOR.
        /// </summary>
        public static string TUTOR {
            get {
                return ResourceManager.GetString("TUTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihláška tutora.
        /// </summary>
        public static string TUTOR_APPLICATION {
            get {
                return ResourceManager.GetString("TUTOR_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přihlášky tutorů.
        /// </summary>
        public static string TUTOR_APPLICATIONS {
            get {
                return ResourceManager.GetString("TUTOR_APPLICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opravdu chcete smazat následujícího uživatele?.
        /// </summary>
        public static string USER_DELETE_CONFIRM {
            get {
                return ResourceManager.GetString("USER_DELETE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail uživatele.
        /// </summary>
        public static string USER_DETAIL {
            get {
                return ResourceManager.GetString("USER_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uživatelé.
        /// </summary>
        public static string USERS {
            get {
                return ResourceManager.GetString("USERS", resourceCulture);
            }
        }
    }
}
